POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "test",
    "author": "test",
    "url": "test",
    "likes": "0"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjM0ZTIwMGUzYWM0ZGM4N2FjOGNkZDEzIiwiaWF0IjoxNjY2MDY1NzIyLCJleHAiOjE2NjYwNjkzMjJ9.tKi9WE1UVhmdr8nZZlY9ChA12X_CK1WUeOCjBAthHok

{
    "title": "testing",
    "author": "testing",
    "url": "testing",
    "likes": "0"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVrYWkiLCJpZCI6IjYzNGUyMDExM2FjNGRjODdhYzhjZGQxNyIsImlhdCI6MTY2NjA2NTc3NywiZXhwIjoxNjY2MDY5Mzc3fQ.TyrUqwCe5hjlPZDIx25lh3zZRv009c5sft5FfqIeOsA

{
    "title": "testing again",
    "author": "testing again",
    "url": "testing.again",
    "likes": "0"
}

